# Generated by Django 4.2.2 on 2024-07-21 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_product_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'description'], 'permissions': [('can_active_product', 'Отменять публикацию продукта.'), ('can_update_product', 'Менять описание любого продукта.'), ('can_update_product_category', 'Менять категорию любого продукта.')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
