# Generated by Django 5.0.6 on 2024-06-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                ("slug", models.CharField(blank=True, max_length=100, null=True)),
                ("content", models.TextField()),
                ("preview", models.ImageField(upload_to="blog/preview")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("published", models.BooleanField(default=False)),
                (
                    "views",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
            ],
            options={
                "verbose_name": "Блог",
                "verbose_name_plural": "Блоговые записи",
            },
        ),
    ]
